### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by idr4n** [akinsho/org-bullets.nvim#25]
Hi,

Would you be interested in adding markdown support for list items? I have tweaked your plugin to use it in markdown files, which looks something like this:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/20104703/186886510-be23acb4-2721-4e42-b229-1b3cc7cca90d.png">

Since the name is `org-bullets`, I understand if you wouldn't want to add markdown support.

Thanks in advance!

**Comment by akinsho** [comment]
@idr4n I'm open to supporting other filetypes. I started this project as more or less a clone of org's plugin but since it can be applied to other filetypes I'm happy to expand it to that, *granted* you are willing to put in the work to get a PR over the line? Whilst it's something I'm open to, I have nowhere near enough time or incentive to dedicate to it myself.

**Comment by idr4n** [comment]
Great @akinsho, in that case I'll clean up my code and put together a PR in the next couple of days. Thanks again!
